var searchData=
[
  ['channeldefinition_0',['ChannelDefinition',['../structcrypto__trader_1_1traders_1_1_coinbase_trader_config_1_1_channel_definition.html',1,'crypto_trader::traders::CoinbaseTraderConfig']]],
  ['channels_1',['channels',['../classcrypto__trader_1_1traders_1_1_coinbase_trader_config.html#a2b7c393e2943492257a9b0c6f45f53a0',1,'crypto_trader::traders::CoinbaseTraderConfig']]],
  ['clear_2',['clear',['../classcrypto__trader_1_1traders_1_1_event_position_manager.html#a4c5bb9e0eb2a62211adf48658f133976',1,'crypto_trader::traders::EventPositionManager']]],
  ['clearall_3',['clearAll',['../classcrypto__trader_1_1traders_1_1_event_position_manager.html#a1113ea40fc004772a73e4897b7e0c925',1,'crypto_trader::traders::EventPositionManager']]],
  ['clienttype_4',['ClientType',['../classcrypto__trader_1_1traders_1_1_coinbase_trader_config.html#a196a6584e664898347751512a4bfbfd5',1,'crypto_trader::traders::CoinbaseTraderConfig']]],
  ['clienttype_5',['clientType',['../classcrypto__trader_1_1traders_1_1_coinbase_trader_config.html#a6db6f8ac27d59799782c5bc252c9bf93',1,'crypto_trader::traders::CoinbaseTraderConfig']]],
  ['close_6',['close',['../classcrypto__trader_1_1protocols_1_1_websocket_client.html#a361e084c862adaa4e4ae443bb5debaab',1,'crypto_trader::protocols::WebsocketClient']]],
  ['coinbase_5fwebsocket_5fclient_2ecpp_7',['coinbase_websocket_client.cpp',['../coinbase__websocket__client_8cpp.html',1,'']]],
  ['coinbase_5fwebsocket_5fclient_2eh_8',['coinbase_websocket_client.h',['../coinbase__websocket__client_8h.html',1,'']]],
  ['coinbase_5fwebsocket_5fclient_5fasync_2ecpp_9',['coinbase_websocket_client_async.cpp',['../coinbase__websocket__client__async_8cpp.html',1,'']]],
  ['coinbase_5fwebsocket_5fclient_5fasync_2eh_10',['coinbase_websocket_client_async.h',['../coinbase__websocket__client__async_8h.html',1,'']]],
  ['coinbasetrader_11',['CoinbaseTrader',['../classcrypto__trader_1_1traders_1_1_coinbase_trader.html',1,'crypto_trader::traders::CoinbaseTrader'],['../classcrypto__trader_1_1traders_1_1_coinbase_trader.html#a668b9a9f86935d5731a00ddad6681754',1,'crypto_trader::traders::CoinbaseTrader::CoinbaseTrader(const CoinbaseTraderConfig &amp;config)'],['../classcrypto__trader_1_1traders_1_1_coinbase_trader.html#afd6e68b97c96b21ce519bf7a5972de61',1,'crypto_trader::traders::CoinbaseTrader::CoinbaseTrader(const CoinbaseTrader &amp;orig)=delete']]],
  ['coinbasetrader_2ecpp_12',['CoinbaseTrader.cpp',['../_coinbase_trader_8cpp.html',1,'']]],
  ['coinbasetrader_2eh_13',['CoinbaseTrader.h',['../_coinbase_trader_8h.html',1,'']]],
  ['coinbasetraderconfig_14',['CoinbaseTraderConfig',['../classcrypto__trader_1_1traders_1_1_coinbase_trader_config.html',1,'crypto_trader::traders::CoinbaseTraderConfig'],['../classcrypto__trader_1_1traders_1_1_coinbase_trader_config.html#a1c6433d5a581efae1ad1de2ade0d049c',1,'crypto_trader::traders::CoinbaseTraderConfig::CoinbaseTraderConfig(const std::shared_ptr&lt; std::atomic_bool &gt; &amp;isRunning, bool paperTrading=false)'],['../classcrypto__trader_1_1traders_1_1_coinbase_trader_config.html#a53cf778d0bb7eaaa076b347f337910dd',1,'crypto_trader::traders::CoinbaseTraderConfig::CoinbaseTraderConfig(const CoinbaseTraderConfig &amp;orig)=default']]],
  ['coinbasewebsocketclient_15',['CoinbaseWebSocketClient',['../classcrypto__trader_1_1adaptors_1_1_coinbase_web_socket_client.html',1,'crypto_trader::adaptors::CoinbaseWebSocketClient'],['../classcrypto__trader_1_1adaptors_1_1_coinbase_web_socket_client.html#a79ecae5dc3f80aeb2b9b09121c217d38',1,'crypto_trader::adaptors::CoinbaseWebSocketClient::CoinbaseWebSocketClient()']]],
  ['coinbasewebsocketclientasync_16',['CoinbaseWebSocketClientAsync',['../classcrypto__trader_1_1adaptors_1_1_coinbase_web_socket_client_async.html',1,'crypto_trader::adaptors::CoinbaseWebSocketClientAsync'],['../classcrypto__trader_1_1adaptors_1_1_coinbase_web_socket_client_async.html#a7cb5e8e3e3eae3310185b66c0371f74d',1,'crypto_trader::adaptors::CoinbaseWebSocketClientAsync::CoinbaseWebSocketClientAsync()']]],
  ['coinbasewebsocketclientasyncconfig_17',['CoinbaseWebSocketClientAsyncConfig',['../structcrypto__trader_1_1adaptors_1_1_coinbase_web_socket_client_async_config.html',1,'crypto_trader::adaptors::CoinbaseWebSocketClientAsyncConfig'],['../structcrypto__trader_1_1adaptors_1_1_coinbase_web_socket_client_async_config.html#a80e33833a12e1c4c0d56edf5b4c9aba5',1,'crypto_trader::adaptors::CoinbaseWebSocketClientAsyncConfig::CoinbaseWebSocketClientAsyncConfig()']]],
  ['coinbasewebsocketclientconfig_18',['CoinbaseWebSocketClientConfig',['../structcrypto__trader_1_1adaptors_1_1_coinbase_web_socket_client_config.html',1,'crypto_trader::adaptors::CoinbaseWebSocketClientConfig'],['../structcrypto__trader_1_1adaptors_1_1_coinbase_web_socket_client_config.html#a7986fe91d20b7deda74c81f953a7ff75',1,'crypto_trader::adaptors::CoinbaseWebSocketClientConfig::CoinbaseWebSocketClientConfig()']]],
  ['commissionrate_19',['commissionRate',['../classcrypto__trader_1_1executors_1_1_paper_trading_executor_config.html#a2f2053fdfea7c269900eb6978dad5265',1,'crypto_trader::executors::PaperTradingExecutorConfig']]],
  ['count_20',['COUNT',['../classcrypto__trader_1_1traders_1_1_coinbase_trader_config.html#a196a6584e664898347751512a4bfbfd5a4905ac9d6a22bdfc1ae096094ce6248d',1,'crypto_trader::traders::CoinbaseTraderConfig']]],
  ['crypto_5ftrader_21',['crypto_trader',['../namespacecrypto__trader.html',1,'']]],
  ['crypto_5ftrader_3a_3aadaptors_22',['adaptors',['../namespacecrypto__trader_1_1adaptors.html',1,'crypto_trader']]],
  ['crypto_5ftrader_3a_3acommon_23',['common',['../namespacecrypto__trader_1_1common.html',1,'crypto_trader']]],
  ['crypto_5ftrader_3a_3adatabases_24',['databases',['../namespacecrypto__trader_1_1databases.html',1,'crypto_trader']]],
  ['crypto_5ftrader_3a_3aexecutors_25',['executors',['../namespacecrypto__trader_1_1executors.html',1,'crypto_trader']]],
  ['crypto_5ftrader_3a_3aprotocols_26',['protocols',['../namespacecrypto__trader_1_1protocols.html',1,'crypto_trader']]],
  ['crypto_5ftrader_3a_3astrategies_27',['strategies',['../namespacecrypto__trader_1_1strategies.html',1,'crypto_trader']]],
  ['crypto_5ftrader_3a_3atraders_28',['traders',['../namespacecrypto__trader_1_1traders.html',1,'crypto_trader']]],
  ['currentholdings_29',['currentHoldings',['../classcrypto__trader_1_1traders_1_1_event_position_manager.html#a8198c07164614ea01c6e4222f18c988c',1,'crypto_trader::traders::EventPositionManager']]]
];
