option(ENABLE_CPPCHECK "Enable static analysis with cppcheck" ON)
option(ENABLE_CLANG_TIDY "Enable static analysis with clang-tidy" OFF)

if (ENABLE_CPPCHECK)
    find_program(CPPCHECK cppcheck)
    if (CPPCHECK)
        configure_file(${CMAKE_SOURCE_DIR}/cmake/naming_addon.json.in ${CMAKE_BINARY_DIR}/naming_addon.json @ONLY)
        set(CMAKE_CXX_CPPCHECK ${CPPCHECK} --suppress=missingInclude --enable=all --addon=${CMAKE_BINARY_DIR}/naming_addon.json)
    else()
        message(SEND_ERROR "cppcheck requested but executable not found")
    endif()
endif()

if (ENABLE_CLANG_TIDY)
    find_program(CLANGTIDY clang-tidy)
    if (CLANGTIDY)
        set(CMAKE_CXX_CLANG_TIDY ${CLANGTIDY})
    else()
        message(SEND_ERROR "clang-tidy requested but executable not found")
    endif()
endif()
