name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: install conan
        run: python3.10 -m pip install conan
      - name: build
        run: make build
      - name: make test
        run: make test
